### ISSUE TITLE
no module named HtmlTestRunner

### ISSUE THREAD

**Issue by anand853** [oldani/HtmlTestRunner#15]
* HtmlTestRunner version:
* Python version:
* Operating System:

### Description

im getting above error in the code , when i use the import statement

### What I Did

```
import HtmlTestRunner
pip install html-testRunner
```

**Comment by oldani** [comment]
Hi, I create an environment in python 2.7 and 3.5, install the library, import it and worked.

**Comment by anand853** [comment]
can you please share the sample class/program

**Comment by oldani** [comment]
I use the same that is in the readme. Do this:

- Create a virtualenv and activate it.
- Run `pip install html-testRunner`
- Then copy the example in the readme, save it to a file `test.py` and run it `python test.py`
