### ISSUE TITLE
XML Reports

### ISSUE THREAD

**Issue by AdiuvoDotFr** [oldani/HtmlTestRunner#18]
* HtmlTestRunner version: 1.1.1
* Python version: 3.6.2
* Operating System: Debian

### Description

Hello.
First, thank you for this wonderful package, love it!

I really have the need for xml results beside html results. Is it something that is comming soon?
Or even if it is not comming soon, may I help with it?

Thank you in advance for your response

**Comment by oldani** [comment]
Hi @AdiuvoDotFr,

It's nice to hear you love it, thank you for that.

For XML results I have been thinking about that, actually, this package was created as a side effect of just having XML reports and needing HTML, there's already an XML report library which uses almost the same API as it, I think we shouldn't rebuild the wheel and use [this package](https://github.com/xmlrunner/unittest-xml-reporting)

**Comment by AdiuvoDotFr** [comment]
Excuse me I did just see your response. For now I don't see how to use it to have both xml and HTML result. I see that an issue already exist for that, and I will continue the conversation here

**Comment by AdiuvoDotFr** [comment]
Oops, did not see that this issue is also closed. Maybe we can discuss that feature?
