### ISSUE TITLE
hello how to fix this one?

### ISSUE THREAD

**Issue by litodagodog** [oldani/HtmlTestRunner#19]
* HtmlTestRunner version: 1.1.1
* Python version: 2.7
* Operating System: Windows 10

from HtmlTestRunner import HtmlTestRunner
ImportError: cannot import name HtmlTestRunner

Process finished with exit code 1

**Comment by AdiuvoDotFr** [comment]
Hello,

I have never tested HtmlTestRunner with python 2.7, but as far as I know oldani has writted in readme.md that it is not compatible for now with python 2.7.

Could you bring more details about your installation? Are you in a virtual env? Have you installed HtmlTestRunner with pip? Don't you have named your file HtmltestRunner (that could explain your error)

**Comment by iPersona** [comment]
It seems that the class name is HTMLTestRunner (**Html**TestRunner -> **HTML**TestRunner)
![bug](https://user-images.githubusercontent.com/3353204/31644581-c1d93384-b329-11e7-8a58-b8e4605b8422.png)
