### ISSUE TITLE
ImportError: cannot import name 'HtmlTestRunner'

### ISSUE THREAD

**Issue by ItsPavan** [oldani/HtmlTestRunner#22]
* HtmlTestRunner version:0.8.3
* Python version: 3.6.2(Anaconda distribution)
* Operating System: Windows 10

### Description

Trying to execute the sample test script with HTMLTestRunner from the test suite

### What I Did

```
from unittest import TestLoader, TestSuite
from HtmlTestRunner import HtmlTestRunner
from Test_cases import TestStringMethods
#import Example2Test

example_tests = TestLoader().loadTestsFromTestCase(TestStringMethods)
#example2_tests = TestLoader().loadTestsFromTestCase(Example2Test)

#suite = TestSuite([example_tests, example2_tests])
suite = TestSuite(example_tests)
runner = HtmlTestRunner(output='example_suite')

runner.run(suite)
```

**Comment by oldani** [comment]
Hi @ItsPavan 

Try ` from HtmlTestRunner import HTMLTestRunner`, sorry i put it bad on documentation i will be fixing it.
