### ISSUE TITLE
Add support unittest.subTest()

### ISSUE THREAD

**Issue by henrywah196** [oldani/HtmlTestRunner#24]
* HtmlTestRunner version: 1
* Python version: 3.6
* Operating System: windows

### Description

does this htmltestRunner support unittest.subTest()?

### What I Did

use htmltestrunner for unittest cases which containing subTest, the result return error instead failure.

**Comment by oldani** [comment]
Hi @henrywah196 

Sorry for the delay here, I have never tried it. Could you supply which error were you getting?

**Comment by CoderHuo** [comment]
Traceback (most recent call last):
  File "test_runner.py", line 11, in <module>
    test = unittest.TestLoader().loadTestsFromTestCase(test_location_type_in_slg)
  File "/usr/local/lib/python3.7/unittest/loader.py", line 86, in loadTestsFromTestCase
    if issubclass(testCaseClass, suite.TestSuite):
TypeError: issubclass() arg 1 must be a class

**Comment by oldani** [comment]
This was implemented by @JamesMTSloan. Now available under version `1.2`
