### ISSUE TITLE
Enhancement - Failure and Error Tracebacks

### ISSUE THREAD

**Issue by jprince14** [oldani/HtmlTestRunner#28]
Enhancement - Failure and Error Tracebacks
* HtmlTestRunner version: 1.1.2
* Python version: 2.7.12 and 3.6.4
* Operating System: Windows 10 and Mint Linux

When a test fails or experiences an error only very limited information about the failure is stored in the report html page. The traceback is printed to console but is not preserved in the html page. One way to obtain this information is demonstrated below where the _exc_str contains the traceback. Can HtmlTestRunner be updated to add this information to the html report.

    def addFailure(self, test, err):

        self.failure_count += 1

        TestResult.addFailure(self, test, err)

        _, _exc_str = self.failures[-1]

**Comment by oldani** [comment]
yes of course, you want to do it by your self?

**Comment by jprince14** [comment]
I'll give it a shot and send you an email with my proposed solution

**Comment by jprince14** [comment]
Attached are files with my proposed changes. I also added an option to specify the outsuffix

[proposed_changes.zip](https://github.com/oldani/HtmlTestRunner/files/1822027/proposed_changes.zip)

**Comment by oldani** [comment]
This has been done by @JamesMTSloan. Released on version `1.2`
