### ISSUE TITLE
Fix Wording in HTML Template (Incorrect English)

### ISSUE THREAD

**Issue by pschluet** [oldani/HtmlTestRunner#30]
* HtmlTestRunner version: 1.1.2
* Python version: 3.6.2
* Operating System: macOS High Sierra (v10.13.3)

### Description

Change the wording in the HTML template from "Total Test Runned" to "Total Tests Run".

### What I Did

Installed HtmlTestRunner and ran the example from the docs.

**Comment by oldani** [comment]
thanks
