### ISSUE TITLE
Can't Combine tests reports in one HTML report

### ISSUE THREAD

**Issue by thomakl** [oldani/HtmlTestRunner#34]
* HtmlTestRunner version: 1.1.2
* Python version: Python 3.6.5
* Operating System: MacOS 10.11

### Description

Hi,
I'm trying to get all my tests results combined in one file. At the moment, everything is separated according to each tests. I read about a new argument in HTMLTestRunner - combine_reports=True, which makes normally all combined in one report.
However I got an error. This  keyword argument is not known from HTMLTestRunner.
Below, the code I tried. It's coming from JamesMTSloan commented on May 8 2018.

### What I Did

```
import unittest
from HtmlTestRunner import HTMLTestRunner

unittest.main(
    testRunner=HTMLTestRunner(
        combine_reports=True,
        add_timestamp=False,
        report_name="MyReports"
    )
)

TypeError: __init__() got an unexpected keyword argument 'combine_reports'

```
Thank you for your time,
Have a nice day!

**Comment by JamesMTSloan** [comment]
Hello,

That is from a pull request that I have proposed but has not (yet?) been accepted into the code base and so is not available from this package. If you want that functionality you could use the code from my own branch and comment there or #32 with any further issues.

**Comment by oldani** [comment]
Thanks to @JamesMTSloan this is already possible on version `1.2`

**Comment by ericrommel** [comment]
I'm still facing that issue with the combine_reports parameters at 1.2.1 version.

* HtmlTestRunner version: 1.2.1
* Python version: 3.7.1
* Operating System: Win10

TypeError: __init__() got an unexpected keyword argument 'combine_reports'

### What I Did
My code:
class HtmlSampleTestSuite(unittest.TestCase):
    def test_sample(self):
        consolidated_test = unittest.TestSuite()
        for name in self.test_names:
            consolidated_test.addTests([
                unittest.defaultTestLoader.loadTestsFromTestCase(test_list[name])
            ])
        html_runner = HtmlTestRunner.HTMLTestRunner(
            report_title='report_title',
            descriptions='descriptions',
            combine_reports=True,
            output=OUTPUT
        )
        html_runner.run(consolidated_test)

if __name__ == '__main__'
    if len(sys.argv) > 1:
        HtmlTestRunnerTestSuite.test_names = sys.argv[1:]
        sys.argv = [sys.argv[0]]
    unittest.main()

**Comment by ishaileshmishra** [comment]
I am not able to combine generate test report, I am using like below, 

runner = HtmlTestRunner.HTMLTestRunner(
            report_title='rest_report',
            descriptions='something',
            combine_reports=True,
        )

What I am missing ?

**Comment by kimfucious** [comment]
I haven't' looked at this in a very long time, but have you tried lower case "true"?

**Comment by ishaileshmishra** [comment]
Yes, I tried. It didn't help
