### ISSUE TITLE
Add functionality to display sub-tests in test case as a tree and display sub-test name

### ISSUE THREAD

**Issue by haykisp** [oldani/HtmlTestRunner#35]
* HtmlTestRunner version: Jinja2==2.9.5->html-testRunner
* Python version: 3.5.2
* Operating System: Ubuntu

### Description
For now sub-tests displayed as a TC. So user see many reports of same TC and not understand which sub-test fails.
So add functionality to display sub-tests in its TC as a tree and display in sub-tests their names.

![screenshot from 2018-08-19 19-38-43](https://user-images.githubusercontent.com/33618822/44310446-83465e80-a3e7-11e8-96b8-f1ef1bd6c712.png)

In this screenshot all TCs have sub-tests

**Comment by JamesMTSloan** [comment]
I feel this package would be incomplete without supporting this. I've attempted to do so in #32.

**Comment by oldani** [comment]
Thanks to the work of @JamesMTSloan this is available now
