### ISSUE TITLE
Enchancement: Show reason of skipping a test

### ISSUE THREAD

**Issue by hannu40k** [oldani/HtmlTestRunner#36]
Currently, the blue "Skip" label is just a static label. It would be useful if the label could be expanded to show reason for skipping.

**Comment by JamesMTSloan** [comment]
Good idea. I've attempted an implementation in #32.

**Comment by oldani** [comment]
Implemented and released under version `1.2`. Thanks @JamesMTSloan  you have done a lot of work for this project
