### ISSUE TITLE
How can i solve testcase name displayed unreadable

### ISSUE THREAD

**Issue by WindInMay524** [oldani/HtmlTestRunner#37]
* HtmlTestRunner version: 1.1.2
* Python version:3.7
* Operating System:windows 10

### Description

![image](https://user-images.githubusercontent.com/38344643/46543465-83e17880-c8f3-11e8-9ab2-020b0a601238.png)

### What I Did

# -*- coding:utf-8 -*-
import requests
import unittest
import HtmlTestRunner
import json
class RequestTest(unittest.TestCase):
    def setUp(self):
        self.url = "http://zzk.cnblogs.com/s/blogpost"
    def test_request(self):
        '''找找看搜索功能'''
        par = {"Keywords": "yoyoketang"}
        result = requests.get('http://zzk.cnblogs.com/s/blogpost', params=par)
        code = result.status_code
        print(result.text)
        self.assertEqual(code,200,"相等")
        assert "博客园" in result.text
if __name__ == '__main__':
    filename = "report.html"
    unittest.main(testRunner=HtmlTestRunner.HTMLTestRunner(output=filename))

**Comment by python012** [comment]
Can you please attach the report file(the html)?

**Comment by python012** [comment]
> * HtmlTestRunner version: 1.1.2
> * Python version:3.7
> * Operating System:windows 10
> 
> ### Description
> ![image](https://user-images.githubusercontent.com/38344643/46543465-83e17880-c8f3-11e8-9ab2-020b0a601238.png)
> 
> ### What I Did
> # -_- coding:utf-8 -_-
> import requests
> import unittest
> import HtmlTestRunner
> import json
> class RequestTest(unittest.TestCase):
> def setUp(self):
> self.url = "http://zzk.cnblogs.com/s/blogpost"
> def test_request(self):
> '''找找看搜索功能'''
> par = {"Keywords": "yoyoketang"}
> result = requests.get('http://zzk.cnblogs.com/s/blogpost', params=par)
> code = result.status_code
> print(result.text)
> self.assertEqual(code,200,"相等")
> assert "博客园" in result.text
> if **name** == '**main**':
> filename = "report.html"
> unittest.main(testRunner=HtmlTestRunner.HTMLTestRunner(output=filename))

Can you please attach the report file(the html)?

**Comment by WindInMay524** [comment]
I have another question either.I can't see the "text information" both in console and html file".
![image](https://user-images.githubusercontent.com/38344643/46725870-b1417400-ccaf-11e8-99b9-0b74e5947612.png)

[report.zip](https://github.com/oldani/HtmlTestRunner/files/2463954/report.zip)

**Comment by oldani** [comment]
For encoding questions, the report by default use `charset=utf8`. If this does not work for you, take the default template and change the encoding.

Regarding of viewing the information in `sdout (console)` this have more to be with the runner than this library, try passing `verbose` to the runner.
