### ISSUE TITLE
There 

### ISSUE THREAD

**Issue by lpapazow** [oldani/HtmlTestRunner#38]
* HtmlTestRunner version: 1.1.2
* Python version: 3.7.0
* Operating System: Windows10

### Description

I want to set a static name for my report that doesn't have the current timestamp suffix.

### What I Did

I tried the following:

```
runner = HTMLTestRunner(output='somedir')
runner.outsuffix = None
```

I saw [here](https://github.com/oldani/HtmlTestRunner/blob/master/HtmlTestRunner/result.py#L334) that if the outsufiix is None or False, timestamp won't be added.

However, I get the following errror:

```
  File "C:\Users\lyubomir.papazov\AppData\Local\Programs\Python\Python37\lib\site-packages\HtmlTestRunner\result.py", line 312, in _report_tests
    testcase_name = test_class_name.split("_")[1]
IndexError: list index out of range
'''

**Comment by oldani** [comment]
This was a bug on the library because of your tests names. It should be fixed on lastest release.
