### ISSUE TITLE
Suggestion: Add junit like xml result file in addition to the html result

### ISSUE THREAD

**Issue by ndinev** [oldani/HtmlTestRunner#4]
I believe that it will be valuable to have **both** html(user readable) and xml(Jenkins readable) results at once.  
It is common case Jenkins to be used for managing test execution, but when failure happens html is the way to manually investigate the problem. However there is no framework providing both file at the same time. 
(There is HTML Report Jenkins plugin that will collect and present nicely the html report)

**Comment by oldani** [comment]
Hey, yeah it could be great to have both and as right now it will be easy to implement, adding to the Todo list of missing features, i will let you know when work in progress:)

**Comment by oxygenxo** [comment]
H, @oldani ! Does this feature available now?
