### ISSUE TITLE
Is there a way to see the assertions of a test

### ISSUE THREAD

**Issue by jonny7** [oldani/HtmlTestRunner#54]
I'm wondering if there is a way to provide all the assertions within a test code in the output. Right now it seems that the following pseudo code:

```python
 def test_func(self):
    assert 1 == 1
    assert 1 == 2
```

Would result in the output

test_func | Fail | Hide
-- | -- | --
AssertionError:Traceback (most recent call last): File "add_person.py", line 56, in test_valid_demographics assert 1 == 2 AssertionError

I'm trying to get a single TC to list all the steps within that test. Something like this 
[output](http://tungwaiyip.info/software/sample_test_report.html)

minds.cgibin.test.test_weblibMultiForm.TestWeblibMultiForm | 6 | 6 | 0 | 0 | Detail
-- | -- | -- | -- | -- | --
test_GET | pass
test_POST_add | pass
test_POST_add_new_tag | pass
test_POST_illegal_tag | pass
test_POST_input_escape | pass
test_POST_remove | pass

Is this currently possible

**Comment by oldani** [comment]
@jonny7 Sorry this is actually not possible
