### ISSUE TITLE
all console print msgs with '\n' show in one in the report

### ISSUE THREAD

**Issue by weitan12** [oldani/HtmlTestRunner#55]
* HtmlTestRunner version: 1.26
* Python version: 2.7.16
* Operating System: linux

### Description

All the console print information show together in the report even I add '\n' in my code for each print

### What I Did
I add few console print msgs in different places in my code, I just want to see the all print information  clearly in the report with every single line. But all print information show as one in the report

How to fix it?

**Comment by weitan12** [comment]
I fixed it by modify the template.
I replace the <p> </p> for the test_case.stdout with <pre><code> </code></pre>

**Comment by cyu-craftnetics** [comment]
Hi,

What did you replace in the template?

**Comment by weitan12** [comment]
I replaced this code in template, please have a try to make sure if it works for you, any problem please let me know.
{%- if test_case.stdout %}<pre><code>{{ test_case.stdout }}</code></pre>{% endif %}


------------------
.


 





------------------ 原始邮件 ------------------
发件人: "cyu-craftnetics"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 凌晨5:30
收件人: "oldani/HtmlTestRunner"<HtmlTestRunner@noreply.github.com>;
抄送: "谭盂😈"<253373565@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [oldani/HtmlTestRunner] all console print msgs with '\n' show inone in the report (#55)




Hi,
 
What did you replace in the template?

**Comment by cyu-craftnetics** [comment]
HI @weitan12 ,

That didn't seem to work for me. What did you replace the code in the template with?
